---
license: CC BY-NC
date: Nov 9, 2023
date-meta: "2023-11-09"
title: The German Protest Registrations Dataset
author: 
 - name: David Pomerenke
   orcid: 0000-0001-5400-4507
url: https://github.com/davidpomerenke/german-protest-registrations
bibliography: [references.bib]
csl: chicago-author-date.csl
echo: false
citation:
  doi: 10.5281/zenodo.10094245
format:
  pdf:
    colorlinks: true
    mainfont: "Lato Light"
    sansfont: "Lato Black"
    link-citations: true
    papersize: a4
    lang: en
    fontsize: 9pt
    header-includes:
     - \usepackage{hyperref}
     - \usepackage[capitalise,noabbrev]{cleveref}
    reference-location: margin
    citation-location: margin
  html:
    mainfont: "Lato Light"
    sansfont: "Lato Black"
    lang: en
    reference-location: margin
    citation-location: margin
  gfm:
    toc: true
    lang: en
abstract: |
  The __German Protest Registrations Dataset__ covers protests that have been registered with demonstration authorities in 17 German cities. The data has been compiled from _Freedom of Information_ requests and covers dates, organizers, topics, the number of registered participants, and for some cities the number of observed participants. Covered date ranges vary, with all cities covered in 2023, and 5 cities covered consistently from 2018 to 2023. In comparison to previous datasets that are largely based on newspaper reports, this dataset gives an unprecented level of detail, and is the largest dataset on protest events in Germany to date. This report gives an overview over existing datasets, explains the data retrieval and processing, displays the properties of the dataset, and discusses its limitations. Code and data are available [on Github](https://github.com/davidpomerenke/german-protest-registrations).
---

## Introduction

This dataset leverages _Freedom of Information_ laws to collect official protest data from 17 different cities in Germany.

__Demonstration authorities.__ The organizers of demonstrations are legally required in Germany (as well as in many other countries) to notify so-called _demonstration authorities_ before the demonstration takes place (Art. 8 Abs. 2 GG, § 14 VersammlG). Demonstration authorities (_Versammlungsbehörden_) in Germany are either part of the police or of the municipal administrations, depending on the region. The authorities keep records of all registered demonstrations. Some protests are not registered in advance, especially more disruptive and illegal protest forms, and they are therefore not contained in these records.

__Freedom of information laws.__ Official documents, including protest records, can be obtained via _Freedom of Information_ laws. These [exist in more than 100 countries](https://en.wikipedia.org/wiki/Freedom_of_information_laws_by_country) and allow anyone to obtain public documents. The specific requirements, exceptions, and costs vary greatly. In Germany, freedom of information exists on the federal level; but many authorities belong to the regional level, where the extent of freedom of information rights [varies greatly](https://transparenzranking.de/); and municipal authorities are not always covered by regional freedom of information laws, sometimes filling the gap with their own legislation.

__Freedom of information platforms.__ Access to public documents has been democratized via platforms that streamline the process of sending requests, escalating the process to oversight authorities or courts if necessary, and making communication and obtained documents available to the public. The [Alaveteli](http://alaveteli.org/) network provides software and hosts such platforms in more than 30 countries across the world. Some independent platforms also exist, such as [Öffentlichkeitsgestz.ch](https://www.oeffentlichkeitsgesetz.ch/) in Switzerland, and _FragDenStaat_ [in Austria](https://fragdenstaat.at/) and [in Germany](https://fragdenstaat.de/). These open the possibility of obtaining official protest data at scale.

## Related work

Multiple approaches have already been used for the creation of datasets on protests in Germany. \cref{tbl-related-work} gives an overview about the existing and new datasets.

__Event databases__ provide disaggregated event data, often on a global scale and with constant updates. The database of choice for protest research is the [_Armed Conflict Location and Event Dataset_](https://acleddata.com/) [ACLED; @raleighIntroducingACLEDArmed2010a]. ACLED is a grand effort that keeps track not only of violent conflicts and riots, but also of ordinary protest events. The data is human-curated based on newspaper reports, and contains coded information on dates, locations, actor groups, police interventions, and more, as well as a short free-text summary for each event, containing an estimate of the size as per the newspaper data source. Data for Germany is available starting from 2020 and is continuously updated. Another relevant event database is the [Global Database of Events, Language, and Tone](https://www.gdeltproject.org/) [GDELT; @leetaruGDELTGlobalData]. It relies completely on the automated processing of newspaper articles, and does not have protest-specific information such as organizers, topics, or number of participants.

__Academic datasets__ have been created through the manual coding of newspaper articles and other sources. [Protestlandschaft Deutschland](https://protestdata.eu/methods) provides interactive visualizations for three German datasets:

  1. [ProDat](https://www.wzb.eu/de/forschung/beendete-forschungsprogramme/zivilgesellschaft-und-politische-mobilisierung/projekte/prodat-dokumentation-und-analyse-von-protestereignissen-in-der-bundesrepublik) [@rucht1992dokumentation] has coded all newspaper articles on Mondays -- as well as all days of every 4th week -- from 1950 to 2002 in _Süddeutsche Zeitung_ and _Frankfurter Rundschau_.
  2. ["Lokale Protestentwicklungen Großstädte"](https://www.fgz-risc.de/forschung/alle-forschungsprojekte/details/BRE_F_04) has coded all articles in _Sächsische Zeitung_ (Dresden), _Leipziger Volkszeitung_, _Stuttgarter Zeitung_, and _Weser-Kurier_ (Bremen) from 2011 to 2020.
  3. ["Lokale Protestentwicklungen Mittelstädte"](https://www.dezim-institut.de/projekte/projekt-detail/lokale-konflikte-um-migration-2-15/) has coded all articles in 12 medium-sized German cities.

Protest events in Germany are also part of international protest datasets: [PolDem](https://poldem.eui.eu/) [@kriesiPoldemProtestDataset2020] provides 3 datasets with different countries and time ranges covered, based on newspaper articles obtained from _NexisLexis_. And the [Mass Mobilization Project](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HTTWYL) [@clarkMassMobilizationProtest2022] records and codes protest events globally from 2014 to 2019.

__Official records__ have been explored only on a small scale: @kanolRightWingExtremistMobilization2021 compiles government responses to opposition requests about right-wing extremist demonstrations in Germany, starting in 2005. And [Demo-Hauptstadt Berlin](https://fragdenstaat.de/dossier/demo‐hauptstadt‐berlin/) has used _Freedom of Information_ requests to obtain data on all demonstrations in Berlin from 2018 to 2023.

::: {.content-visible when-format="markdown"}
| **Dataset** | **Source** | **Start** | **End** | **Topics?** | **Reg?** | **Obs?** | **#Cities** | **#Events** |
|-------------|------------|-----------|---------|-------------|----------|----------|-------------|-------------|
| ACLED | newspapers, ... | 2020 | ongoing | ✓ |  | ✓ | all | 13,250 |
| ProDat | newspapers | 1950 | 2002 | ✓ |  | ✓ | all | 15,973 |
| Lokale Protestentw. Großstädte | newspapers | 2011 | 2020 | (✓) |  | ✓ | 4 | 4,708 |
| Lokale Protestentw. Mittelstädte | newspapers | 2014 | 2018 | (✓) |  | ✓ | 12 | 1,988 |
| PolDem 30 | newspapers | 2000 | 2015 | (✓) |  | ✓ | all | 2,252 |
| PolDem 6 | newspapers | 1975 | 2011 | ✓ |  | ✓ | all | 8,887 |
| PolDem EU | newspapers | 1995 | 2009 | ✓ |  | ✓ | all | 56 |
| Mass Mobilization Project | newspapers | 1990 | 2014 | ✓ |  | ✓ | all | 364 |
| Right-Wing Extremist Mobilization | government | 2005 | 2020 | ✓ |  | ✓ | all | 3,290 |
| Demo-Hauptstadt Berlin | dem. auth. | 2018 | 2020 | ✓ | ✓ | ✓ | 1 | 12,775 |
| German Protest Reg. 2023 | dem. auth. | 2023 | 2023 | ✓ | ✓ | (✓) | 12 | 6,400 |
| German Protest Reg. 2018-2023 | dem. auth. | 2018 | 2023 | ✓ | ✓ | (✓) | 4 | 14,548 |
| German Protest Reg. (all) | dem. auth. | 2012/.../2023 | 2023 | ✓ | (✓) | (✓) | 17 | 70,330 |
:::

::: {.content-visible unless-format="markdown"}
\begin{table}[!ht]
    \caption{Comparison of existing datasets and the presented dataset.}
    \label{tbl-related-work}
    \centering
    \small\selectfont
    \begin{tabular}{llcccccrr}
    \hline
        \textbf{Dataset} & \textbf{Source} & \textbf{Start} & \textbf{End} & \textbf{Topics?} & \textbf{Reg?} & \textbf{Obs?} & \textbf{\#Cities} & \textbf{\#Events} \\ \hline
        ACLED & newspapers, ... & 2020 & ongoing & $\checkmark$ &  & $\checkmark$ & all & 13.250 \\
        ProDat & newspapers & 1950 & 2002 & $\checkmark$ &  & $\checkmark$ & all & 15.973 \\
        Lokale Protestentw. Großstädte & newspapers & 2011 & 2020 & ($\checkmark$) &  & $\checkmark$ & 4 & 4.708 \\
        Lokale Protestentw. Mittelstädte & newspapers & 2014 & 2018 & ($\checkmark$) &  & $\checkmark$ & 12 & 1.988 \\
        PolDem 30 & newspapers & 2000 & 2015 & ($\checkmark$) &  & $\checkmark$ & all & 2252 \\
        PolDem 6 & newspapers & 1975 & 2011 & $\checkmark$ &  & $\checkmark$ & all & 8.887 \\
        PolDem EU & newspapers & 1995 & 2009 & $\checkmark$ &  & $\checkmark$ & all & 56 \\
        Mass Mobilization Project & newspapers & 1990 & 2014 & $\checkmark$ &  & $\checkmark$ & all & 364 \\
        Right-Wing Extremist Mobilization & government & 2005 & 2020 & $\checkmark$ &  & $\checkmark$ & all & 3.290 \\
        Demo-Hauptstadt Berlin & dem. auth. & 2018 & 2020 & $\checkmark$ & $\checkmark$ & $\checkmark$ & 1 & 12.775 \\
        German Protest Reg. 2023 & dem. auth. & 2023 & 2023 & $\checkmark$ & $\checkmark$ & ($\checkmark$) & 12 & 6.400 \\
        German Protest Reg. 2018-2023 & dem. auth. & 2018 & 2023 & $\checkmark$ & $\checkmark$ & ($\checkmark$) & 4 & 14.548 \\
        German Protest Reg. (all) & dem. auth. & 2012/.../2023 & 2023 & $\checkmark$ & ($\checkmark$) & ($\checkmark$) & 17 & 70.330 \\ \hline
    \end{tabular}
\end{table}
:::

<!-- Lokale Konfliktdynamiken im Vergleich: Bremen 1178, Dresden 1147, Leipzig 1274, Stuttgart 1109
Lokale Konflikte um Migration: Celle 200, Düren 125, Esslingen 188, Herten 96, Husum 82, Neubrandenburg 219, Neuruppin 155, Offenburg 211, Plauen 376, Rendsburg 90, Weilheim 118, Wismar 128 -->

## Methods

__Retrieval.__ I send freedom of information requests to German demonstration authorities (depending on the region these are either part of the municipal administrations or of the police) and their supervisory bodies concerning protest data in 32 cities. These cities comprise the political capitals of all 16 regions in Germany, the 17 largest cities by population size, as well as some smaller cities for regions where the request in the regional capital is unsuccessful. 4 requests are not answered, 2 are rejected, 5 state that they do not possess such data, 2 have to be withdrawn due to demanded payments of multiple hundreds of euros, and 19 are partially or completely successful.[^unsuccess] The requests and responses including the original data files can be found at [FragDenStaat](https://fragdenstaat.de/anfragen/?q=demonstration+csv&first_after=2022-12-01&first_before=2023-07-31).

[^unsuccess]: Not answered: Bochum, Essen, Düsseldorf, Chemnitz. Rejected: Hannover, Frankfurt am Main. No information available: Hamburg, Leipzig, Nürnberg, Schwerin, Rostock. Redrawn due to high costs: Stuttgart, Halle (Saale).

__Processing.__ I convert all files to CSV using the _pandas_ library [@reback2020pandas], _Adobe PDF Converter_, and _PdfTables.com_. Since the column names and formats vary widely, I create a separate table reader script for each city. For the challenge of I use the [_dateparser_](https://github.com/scrapinghub/dateparser) library (parsing about 90% of dates), hand-written regex rules based on the most common patterns in the data (parsing about 9% of the data), and manual coding for the remaining data points. Multi-day events are reduced to their start date. When a single data point describes multiple events, it is reduced to the first day of the first event. Data points without date information are dropped. Participant numbers are also parsed using a combination of regex rules and manual coding; specifiers such as "max.", "min.", "bis zu" are ignored, and for number ranges the rounded average is applied. The dataset for Augsburg cannot be converted from PDF to CSV, the dataset for Mannheim is poorly structured, and the dataset for Dortmund does not have topic information, so I exclude them.

## Results

The resulting dataset contains 70.330 events from 17 cities. For 14 cities the ex-ante number of expected participants are given, and for 2 of them (Berlin and Magdeburg) the ex-post extimates by the police are also included. For all cities the topic of the protest is given, as specified by the organizers themselves; and for 4 cities (Erfurt, München, Wiesbaden, Wuppertal) the name of the organizing group is also known.

\begingroup
\scriptsize\selectfont
```{python}
# | label: tbl-overview
# | tbl-cap: Overview of the German Protest Registrations dataset. _kpop_ = population in 1000; _cap?_ = whether the city is the political capital of its region; _reg?_ = whether the number of registered protesters (as per the organizers) is available; _obs?_ = whether the number of observed protesters (as per the police) is available; _12 ... 23_ = number of records per city from 2012 to 2023.
import pandas as pd
from IPython.display import Markdown, Latex
from german_protest_registrations.data_description import pretty_overview_table

df = pretty_overview_table(symbol="x")
df = df.rename(columns={"#reg?": "reg?", "#obs?": "obs?"})
Markdown(df.to_markdown(index=False))
# Latex(df.to_latex(index=False, position="h!"))
```
\endgroup

Further statistics about the dataset can be seen in table @tbl-overview. @fig-map shows the regional coverage of the dataset.

```{python}
# | label: fig-map
# | fig-cap: "Map of regions that are covered by the dataset. Dark blue region have data for their capital city, including information on the number of participants. Light blue region have some data but do not fulfil both criteria (BW, NRW: capital not covered; TH: no participant info). Grey regions (HH, MV, NI) have no data at all."
# | column: margin
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib_inline.backend_inline import set_matplotlib_formats

from german_protest_registrations.data_map import get_map

set_matplotlib_formats("png")

fig, ax = get_map()
plt.show()
```

As apparent from @tbl-overview, the covered years vary between cities. Using the whole dataset unfiltered would therefore lead to inconsistencies in developments over time. Therefore the dataset is provided in three subsets (see also the bottom of \cref{tbl-related-work}):

1. The __2018-2023 dataset__ contains only cities that have coverage throughout 2018-2023, and that also have the number of registered participants available. This results in a dataset of about 14.500 entries that strikes a balance between regional diversity (4 cities) and time coverage (6 years).
2. The __2023 dataset__ contains all cities that have data available in 2023, and also have the number of registered participants available. With 12 cities covered and 6.400 overall entries, it is useful especially for the study of geographic variations.
3. The __unfiltered dataset__ contains all data without restrictions on included cities and time ranges, overall 70.330 entries. It also contains cities where the number of registered participants is not available. This dataset should _not_ be used for direct analysis; but it may be used for the creation of alternative consistent sub-datasets similar to the two ones above.

```{python}
# | label: fig-time
# | fig-cap: "History of the number of protest events per week in the dataset. Since the various cities have different coverage timespans, the number of events is subject to large systematic changes in the unfiltered datasets. Two subsets have been created where the included cities are constant: One contains all cities that have coverage throughout 2018-2023; and one contains all cities with coverage in 2023."
# | column: page

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from german_protest_registrations.unify import get_all_datasets

dfs = get_all_datasets()
dfs[0]["dataset"] = "2023"
dfs[1]["dataset"] = "2018 - 2023"
dfs[2]["dataset"] = "2012/.../2023 - 2023 (inconsistent)"
df = pd.concat(dfs)
df = (
    df
    .sort_values(by=["dataset"])
    .groupby(["date", "dataset"])
    .size()
    .unstack()
    .fillna(0)
    .astype(int)
    .reset_index()
)
df["date"] = pd.to_datetime(df["date"])
df = df.set_index("date")
df = df.resample("1M").sum()
# df = df.replace(0, np.nan)
df.plot(
    figsize=(14, 1.5),
    title="Weekly number of protests in the dataset (all cities)",
    linewidth=1.5,
    ylabel="#protests",
)
plt.show()
```

## Discussion and Limitations

The main __benefits__ of authority data are:

1. __Level of detail:__ Many more events (per timeframe, and overall) are included than in any existing dataset based on newspaper analyses.
2. Avoidance of __selection bias__ of the media. This is feared to be an immense problem associated with newspaper-based data [@hutterProtestEventAnalysis2014; @jamesozdenLiteratureReviewProtest2022]. This dataset may also help examining the actual amount of media selection bias.

The two main __downsides__ of using data from demonstration authorities are:

1. __Unreliability:__ Since the data is only about registrations, we do not know whether the events have actually taken place, and how many people have actually participated. (Only for some cities -- Berlin and Magdeburg -- we can know it via the numbers of observerd participants, and for other cities -- München -- via indications of cancelled events.)
2. __Incompleteness:__
   - Not all protests are registered. Some disruptive groups such as _Letzte Generation_ deliberately do _not_ register many of their protest actions.
   - Only a handful of municipalities are included, focusing on large and politically relevant cities and ignoring the places of residence of more than 85% of the population.

__Criticisms of authority data.__ Protest research has identified two main sources of protest event data -- newspaper data and data from authorities -- and overwhelmingly relies on the first source, that is newspaper data. Objections are raised against the use of data from demonstration authorities, as being biased, uninformative about the motives and organizers, uncomparable across regions, often unavailable or unobtainable, and because it is restricted to only registered demonstrations [@hutterProtestEventAnalysis2014, @ProtestlandschaftDeutschland, @wiedemannGeneralizedApproachProtest2022].

I agree with these objections only in part:

- With _Freedom of Information_ laws and platforms such as _FragDenStaat_ it is now possible to obtain this data easily, cheaply, and at scale -- however with the exception of regions with weak _Freedom of Information_ laws or poor data management (see @fig-map). 
- In 17 out of 19 cities the data contains information about the topics of the demonstrations, as specified by the organizers; this may well give a better perspective on the organizers and their motives than subsequent newspaper coverage may give. 
- The data from demonstration authorities avoids both media bias in judging the goals of the organizers, as well as media bias in the selection of events worth reporting, and is thus arguably _less_ biased than media-derived data. Only the numbers of participants are judged by the police and may be subject to bias, just as the estimates by journalists may also be subject to bias; researchers will be aware of topics where this may be especially problematic, such as anti-police protests. 
- Regarding the issue of comparability, the current datasets are specifially designed to be comparable across regions, by focusing on key information that exists in all regions in similar formats.

<!-- __Causal inference for protest impact evaluation.__ The dataset is not suitable for one widespread method, that is, _instrumental variables_ using weather data. Rather, it is especially suited to _synthetic control_ analyses. -->

## Conclusion

The _German Protest Registrations_ dataset presents opportunities for more detailed and less biased protest event analysis. Researchers should be aware of reliability problems with this type of data, and of the exclusion of non-registered protests. While the unfiltered dataset comes with inconsistent data over time, two consistent subsets are provided and researchers are encouraged to create their own consistent subsets. The dataset may drive insights internal to protest research -- such as the relation between registration and observation data --, as well as to applications such as protest impact evaluation.

## Contact

Please contact me via email to <firstnamelastname@mailbox.org>, or using the discussion and issue features [on Github](https://github.com/davidpomerenke/german-protest-registrations).

## References
